name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    name: Build-android
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flutter_client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@master

      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle

      - run: cp -r ./build ../build

      - uses: actions/upload-artifact@v3
        with:
          name: android-build
          path: build/app/outputs/apk/release/app-release.apk
  build-ios:
    name: Build-ios
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./flutter_client
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@master
        with:
          channel: "stable"
          architecture: x64

      - run: flutter pub get

      - run: pod repo update
        working-directory: ./flutter_client/ios

      - run: flutter build ios --release --no-codesign

      - run: zip -r -9 FlutterIpaExport.ipa build/ios/iphoneos/Runner.app/

      - run: mkdir ../build
      - run: cp FlutterIpaExport.ipa ../build

      - uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/
  build-web:
    name: Build-web
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    defaults:
      run:
        working-directory: ./flutter_client
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@master
        with:
          channel: stable

      - run: flutter pub get
      - run: flutter build web --base-href /web/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: true
          default_prerelease_bump: false
          dry_run: true

      - uses: docker/metadata-action@v5
        id: bot_client_image_meta
        with:
          images: ghcr.io/${{github.repository_owner}}/bot_client_web
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}},value=${{ steps.tag_version.outputs.new_tag }}

      - name: Build and push bot service docker image to GHCR and Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./
          file: ./Dockerfile
          tags: ${{ steps.bot_client_image_meta.outputs.tags }}
          labels: ${{ steps.bot_client_image_meta.outputs.labels }}
          target: web
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-linux:
    name: Build-linux
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flutter_client
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@master
        with:
          channel: stable

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - run: flutter pub get
      - run: flutter build linux

      - run: cp -r ./build ../build

      - uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: build/linux/x64/release/bundle/
  build-windows:
    name: Build-windows
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./flutter_client
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@master
        with:
          channel: stable

      - run: flutter pub get
      - run: flutter build windows

      - run: cp -r ./build ../build

      - uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/windows/runner/Release
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - Build-ios
      - Build-android
      - Build-web
      - Build-linux
      - Build-windows
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - run: zip -r -9 assets.zip artifacts/

      - id: changelog_generator
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          unreleased: false

      - id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: true
          default_prerelease_bump: false

      - id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.changelog_generator.outputs.changelog }}
          draft: false
          prerelease: false
          files: |
            assets.zip
            artifacts/android-build/*
            artifacts/ios-build/*
            artifacts/windows-build/*
            artifacts/linux-build/*
