name: Build mobile apps
on:
  push:
    tags:
      - "*"

jobs:
  build-android:
    name: Build android
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flutter_client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.9"
      - name: Install dependencies
        run: flutter pub get
      - name: Generate l10n
        run: flutter gen-l10n
      - name: Build apk
        run: flutter build apk
      - name: Build appbundle
        run: flutter build appbundle

      - uses: actions/upload-artifact@master
        with:
          name: android-build
          path: build/app/outputs/apk/release/
  build-ios:
    name: Build ios
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./flutter_client
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - name: Install dependencies
        run: flutter pub get
      - name: Generate l10n
        run: flutter gen-l10n
      - name: Build ios
        run: flutter build ios --release --no-codesign

      - uses: actions/upload-artifact@master
        with:
          name: ios-build
          path: build/ios/ipa
  release:
    name: create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
      - uses: ncipollo/release-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "ios-build,android-build"
          body: "new release"
